"""New Initial

Revision ID: 2ec397edd6e6
Revises: 
Create Date: 2025-04-15 10:56:13.541907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ec397edd6e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Company',
    sa.Column('company_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('EmissionFactor',
    sa.Column('factor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('factor_name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('factor_id')
    )
    op.create_table('Role',
    sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=True),
    sa.Column('scope', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('User',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('account'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Product',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('product_type', sa.String(length=100), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['Company.company_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('Project',
    sa.Column('project_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['Company.company_id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('CF_Result',
    sa.Column('cf_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('total_emission', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('record_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['Product.product_id'], ),
    sa.PrimaryKeyConstraint('cf_id')
    )
    op.create_table('UserRole',
    sa.Column('user_role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('scope_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['Role.role_id'], ),
    sa.ForeignKeyConstraint(['scope_id'], ['Project.project_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('user_role_id')
    )
    op.create_table('CF_Activity',
    sa.Column('activity_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cfr_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.Enum('raw_material', 'manufacturing', 'transportation', 'use', 'diposal'), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('value', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('factor_id', sa.Integer(), nullable=True),
    sa.Column('transpor_origin', sa.String(length=255), nullable=True),
    sa.Column('transport_method', sa.String(length=255), nullable=True),
    sa.Column('distance_per_trip', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('distance_unit', sa.String(length=50), nullable=True),
    sa.Column('usage_ratio', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('allocation_ratio', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('fuel_input_per_unit', sa.Float(), nullable=True),
    sa.Column('fuel_input_unit', sa.String(length=255), nullable=True),
    sa.Column('land_transport_tkm', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cfr_id'], ['CF_Result.cf_id'], ),
    sa.ForeignKeyConstraint(['factor_id'], ['EmissionFactor.factor_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['Project.project_id'], ),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_table('Report',
    sa.Column('report_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_name', sa.String(length=255), nullable=True),
    sa.Column('cfv_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cfv_id'], ['CF_Result.cf_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Report')
    op.drop_table('CF_Activity')
    op.drop_table('UserRole')
    op.drop_table('CF_Result')
    op.drop_table('Project')
    op.drop_table('Product')
    op.drop_table('User')
    op.drop_table('Role')
    op.drop_table('EmissionFactor')
    op.drop_table('Company')
    # ### end Alembic commands ###
